-- Public marketing / SEO settings (editable from admin.wwebconsole.com)

INSERT OR IGNORE INTO app_settings (key, value, updated_at) VALUES
  ('site_name', 'WWebConsole', strftime('%s','now') * 1000),
  ('site_tagline', 'WeatherLink console for the web', strftime('%s','now') * 1000),
  ('site_description', 'WWebConsole is a cloud weather console for Davis WeatherLink stations. Live dashboard, TV share links, and secure WeatherLink API credentials — free to start.', strftime('%s','now') * 1000),
  ('site_keywords', 'WeatherLink, Davis Instruments, weather console, weather dashboard, WeatherLink Live, TV weather display, weather station', strftime('%s','now') * 1000),
  ('site_og_image', 'https://wwebconsole.com/og.png', strftime('%s','now') * 1000),
  ('site_canonical_base', 'https://wwebconsole.com', strftime('%s','now') * 1000),
  ('site_twitter_handle', '', strftime('%s','now') * 1000),
  ('site_support_email', 'support@wwebconsole.com', strftime('%s','now') * 1000),
  ('site_company_name', 'APEXs Inc', strftime('%s','now') * 1000),
  ('site_footer_text', 'Built for Davis WeatherLink stations. Cloud console on Cloudflare.', strftime('%s','now') * 1000),
  ('seo_home_title', 'WWebConsole — WeatherLink console for the web', strftime('%s','now') * 1000),
  ('seo_home_description', 'Live WeatherLink dashboard, TV share links, and secure cloud credentials. Start free for 30 days.', strftime('%s','now') * 1000),
  ('seo_features_title', 'Features — WWebConsole', strftime('%s','now') * 1000),
  ('seo_features_description', 'Live weather dashboard, WeatherLink v1/v2 API, TV share URLs, account security, and admin controls.', strftime('%s','now') * 1000),
  ('seo_pricing_title', 'Pricing — WWebConsole', strftime('%s','now') * 1000),
  ('seo_pricing_description', 'Free trial, then yearly per-device pricing for WeatherLink Pro stations. Cancel anytime.', strftime('%s','now') * 1000),
  ('seo_about_title', 'About — WWebConsole', strftime('%s','now') * 1000),
  ('seo_about_description', 'Why we built WWebConsole: a modern web console for Davis WeatherLink without local servers.', strftime('%s','now') * 1000),
  ('seo_contact_title', 'Contact — WWebConsole', strftime('%s','now') * 1000),
  ('seo_contact_description', 'Get in touch with the WWebConsole team for support, billing, or partnership questions.', strftime('%s','now') * 1000),
  ('seo_privacy_title', 'Privacy Policy — WWebConsole', strftime('%s','now') * 1000),
  ('seo_privacy_description', 'How WWebConsole collects, stores, and protects your account and WeatherLink data.', strftime('%s','now') * 1000),
  ('seo_terms_title', 'Terms of Service — WWebConsole', strftime('%s','now') * 1000),
  ('seo_terms_description', 'Terms governing use of WWebConsole, billing, and WeatherLink integrations.', strftime('%s','now') * 1000),
  ('seo_changelog_title', 'Changelog — WWebConsole', strftime('%s','now') * 1000),
  ('seo_changelog_description', 'Product updates and release notes for WWebConsole.', strftime('%s','now') * 1000),
  ('home_hero_headline', 'Your WeatherLink station, on the web', strftime('%s','now') * 1000),
  ('home_hero_subhead', 'Secure cloud console for Davis WeatherLink. Live dashboard, TV share links, and admin-ready accounts — start free.', strftime('%s','now') * 1000),
  ('home_hero_cta_primary', 'Start free', strftime('%s','now') * 1000),
  ('home_hero_cta_secondary', 'See pricing', strftime('%s','now') * 1000),
  ('home_features_json', '[{"title":"Live dashboard","body":"Temperature, wind, rain, pressure, and sun times from your WeatherLink station."},{"title":"TV share links","body":"Fullscreen public URLs for lobbies, offices, and wall displays."},{"title":"Secure credentials","body":"WeatherLink API keys encrypted at rest. Choose v1 or v2 — never both."},{"title":"Cloud-native","body":"Runs on Cloudflare Workers worldwide. No local server to babysit."}]', strftime('%s','now') * 1000),
  ('pricing_headline', 'Simple yearly pricing', strftime('%s','now') * 1000),
  ('pricing_subhead', 'Try free, then pay per device when you need continuous Pro polling.', strftime('%s','now') * 1000),
  ('pricing_basic_blurb', 'Free trial access with Basic WeatherLink polling (about every 15 minutes). Perfect to evaluate the console.', strftime('%s','now') * 1000),
  ('pricing_pro_blurb', 'Yearly per device for WeatherLink Pro stations. Faster polling and continuous access after the trial.', strftime('%s','now') * 1000),
  ('pricing_footnote', 'Paid plans require a WeatherLink Pro subscription from Davis. Activate devices from your account or ask an admin.', strftime('%s','now') * 1000),
  ('about_body', 'WWebConsole is a cloud weather console for Davis WeatherLink stations. We built it so you can monitor stations from any browser, share a TV display URL, and keep API credentials encrypted — without running a local server.\n\nThe product runs on Cloudflare Workers and D1, with optional Turnstile bot protection and email verification.', strftime('%s','now') * 1000),
  ('contact_intro', 'Questions about billing, WeatherLink setup, or enterprise access? Email us and we will get back to you.', strftime('%s','now') * 1000),
  ('privacy_body', '## Overview\nWWebConsole (“we”, “us”) provides a web console for Davis WeatherLink stations. This policy explains what we collect and why.\n\n## Account data\nWe store your email, optional name, password hash, and account status. If email verification is enabled, we temporarily store one-time codes.\n\n## WeatherLink credentials\nAPI keys and secrets you enter are encrypted at rest and used only to fetch weather data for your account. We do not sell credential data.\n\n## Usage data\nWe store station configuration, cached weather payloads, share-link slugs, and billing/trial timestamps needed to operate the service.\n\n## Cookies\nWe use a session cookie to keep you signed in. Theme preference may be stored in local browser storage.\n\n## Retention & deletion\nYou can schedule account deletion from Account settings. After the grace period, account data is purged. Contact support for earlier assistance.\n\n## Contact\nEmail the address shown on the Contact page for privacy requests.', strftime('%s','now') * 1000),
  ('terms_body', '## Agreement\nBy using WWebConsole you agree to these terms.\n\n## Service\nWe provide a best-effort cloud console for WeatherLink data. WeatherLink and Davis Instruments are third parties; their APIs and plans are outside our control.\n\n## Accounts\nYou are responsible for safeguarding your password and for activity under your account. Do not share credentials that you are not authorized to use.\n\n## Billing\nFree trial length and yearly pricing are shown on the Pricing page and may change. Paid device access may require WeatherLink Pro. Refunds are handled case-by-case.\n\n## Acceptable use\nDo not abuse the service, attempt unauthorized access, or use share links for unlawful content.\n\n## Disclaimer\nThe service is provided “as is” without warranties. We are not liable for weather data accuracy, API outages, or consequential damages to the extent permitted by law.\n\n## Changes\nWe may update these terms; continued use after changes constitutes acceptance.\n\n## Contact\nUse the Contact page for legal or billing questions.', strftime('%s','now') * 1000),
  ('changelog_body', '## 2026-07-09\n- Marketing site and SEO pages\n- Admin-configurable site & SEO settings\n- Account email/password change and 15-day deletion grace\n- Light theme default with dark mode\n- WeatherLink v1 or v2 credentials (exclusive)\n\n## Earlier\n- Cloudflare Workers + D1 rewrite\n- Auth, Turnstile, Resend OTP\n- Free trial and yearly per-device Pro\n- TV share links and admin console', strftime('%s','now') * 1000),
  ('robots_extra', '', strftime('%s','now') * 1000),
  ('seo_indexable', '1', strftime('%s','now') * 1000);
