#!/usr/bin/env bash
# Sync selected keys from .env → .dev.vars for local `wrangler` / Vite.
# Usage: npm run env:sync-dev
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${ROOT}/.env"
OUT="${ROOT}/.dev.vars"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing .env — copy .env.example to .env and fill values." >&2
  exit 1
fi

python3 - "$ENV_FILE" "$OUT" <<'PY'
import sys
from pathlib import Path

env_path, out_path = map(Path, sys.argv[1:3])
vals = {}
for line in env_path.read_text(encoding="utf-8").splitlines():
    s = line.strip()
    if not s or s.startswith("#") or "=" not in s:
        continue
    k, _, v = s.partition("=")
    k, v = k.strip(), v.strip()
    if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
        v = v[1:-1]
    vals[k] = v

# Keys Wrangler/local Worker needs
keys = [
    "SESSION_SECRET",
    "CREDENTIALS_KEY",
    "ADMIN_EMAIL",
    "ADMIN_EMAILS",
    "TURNSTILE_SECRET_KEY",
    "RESEND_API_KEY",
    "CLOUDFLARE_API_TOKEN",
    "CLOUDFLARE_ACCOUNT_ID",
]
# Prefer LOCAL_APP_URL for local APP_URL
app_url = vals.get("LOCAL_APP_URL") or vals.get("APP_URL") or "http://localhost:5173"

lines = [
    "# Generated by npm run env:sync-dev from .env — do not commit",
    f"APP_URL={app_url}",
]
for k in keys:
    if vals.get(k):
        lines.append(f"{k}={vals[k]}")

out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
out_path.chmod(0o600)
print(f"Wrote {out_path} ({len(lines)-1} keys)")
PY
